name: Validate Email
description: "Check if an email address is valid."
branding:
    icon: "mail"
    color: "green"
inputs:
    email:
        description: "The email address to validate."
        required: true
outputs:
    result:
        description: "The result of the validation."
runs:
    using: "node16"
    main: "dist/index.js"
