name: Action

on:
    push:
        branches: [main]

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-action
    cancel-in-progress: true

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Dependencies
              run: |
                  npm install
                  npm install -g @vercel/ncc

            - name: Build
              run: ncc build index.js --license licenses.txt

            - name: Commit
              run: |
                  git config --global user.email "bot@williamharrison.dev"
                  git config --global user.name "WDH-Bot"
                  git add dist/
                  git commit -m "chore: build package"
                  git push
